apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
stringData:
  admin-user: admin
  admin-password: REPLACE_ME
---
# Copie este arquivo para grafana-admin-secret.yaml e troque a senha antes do deploy.
