apiVersion: v1
kind: Service
metadata:
  name: casaos-service
  namespace: casaos
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: casaos-service
  namespace: casaos
subsets:
  - addresses:
      - ip: 192.168.100.113
    ports:
      - port: 8081
        protocol: TCP
