apiVersion: v1
kind: Service
metadata:
  name: casaos-service
  namespace: casaos
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
