---
apiVersion: v1
kind: Service
metadata:
  name: casaos-external
  namespace: tools
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: casaos-external-1
  namespace: tools
  labels:
    kubernetes.io/service-name: casaos-external
addressType: IPv4
ports:
  - name: http
    port: 8081
    protocol: TCP
endpoints:
  - addresses:
      - 192.168.100.113
