---
environment_name: prod
base_domain: home.arpa
server_lan_ip: "{{ ansible_host }}"
server_lan_interface: ""
lan_cidr: 192.0.2.0/24
vpn_cidr: ""
base_timezone: Etc/UTC
k3s_version: v1.36.3+k3s1
k3s_pod_cidr: 10.42.0.0/16
k3s_service_cidr: 10.43.0.0/16
k3s_flannel_interface: ""
base_admin_user: "{{ ansible_user }}"
