---
- name: Deploy Docker services
  hosts: homeserver
  become: yes

  vars:
    remote_project_path: "/opt/docker_apps"

  tasks:
    - name: Create project directory on the server
      file:
        path: "{{ remote_project_path }}"
        state: directory
        mode: '0755'

    - name: Create Prometheus config directory on the server
      file:
        path: "{{ remote_project_path }}/prometheus"
        state: directory
        mode: '0755'

    - name: Copy docker-compose file to the server
      copy:
        src: "docker_files/docker-compose.yml"
        dest: "{{ remote_project_path }}/docker-compose.yml" 

    - name: Copy Prometheus config to the server
      copy:
        src: "docker_files/prometheus/prometheus.yml"
        dest: "{{ remote_project_path }}/prometheus/prometheus.yml"

    - name: Stop and remove existing Docker applications
      community.docker.docker_compose:
        project_src: "{{ remote_project_path }}"
        state: absent
        remove_orphans: yes

    - name: Prune unused Docker networks
      command: docker network prune -f
      changed_when: false

    - name: Ensure Docker applications are running
      community.docker.docker_compose:
        project_src: "{{ remote_project_path }}"
        state: present
        remove_orphans: yes