---
- name: Configure Home Server
  hosts: server
  become: yes
  tasks:
    - name: Update APT cache and install base packages
      apt:
        name:
          - git
          - vim
          - htop
          - curl
          - ca-certificates
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up the Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Add user to the 'docker' group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes