---
kubeconfig_path: /etc/rancher/k3s/k3s.yaml
traefik_namespace: kube-system
traefik_release_name: traefik
traefik_tls_secret_name: traefik-tls
traefik_tls_mount_path: /certs
traefik_dynamic_config_path: /tmp/home-server-traefik-helmchartconfig.yaml
local_tls_cert_path: "{{ playbook_dir }}/secrets/{{ environment_name }}-tls.crt"
local_tls_key_path: "{{ playbook_dir }}/secrets/{{ environment_name }}-tls.key"
cockpit_port: 9090
